name = "quizzing"
compatibility_date = "2022-05-22"
main = "dist-worker/handler.mjs"
routes = ["quizzing.pages.dev/*"]
workers_dev = true

[miniflare]
env_path = ".env.local"

[build]
command = "pnpm worker:build"