name = "quizzing"
compatibility_date = "2022-05-22"
main = "dist-worker/handler.js"
routes = ["api.quizzing.ninja/*"]
workers_dev = true

[miniflare]
env_path = ".env.local"

[build]
command = "yarn worker:build"